In [10]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
z=x+y
np.add(x,y)

array([[  6.,   8.],
       [ 10.,  12.]])

In [11]:
np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [12]:
np.multiply(x, y)

array([[  5.,  12.],
       [ 21.,  32.]])

In [13]:
np.divide(x, y)

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [14]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [18]:
# We instead use the dot function to compute inner products of vectors,
#to multiply a vector by a matrix, and to multiply matrices.

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [19]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [20]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [22]:
v = np.array([9,10])
w = np.array([11, 12])
v,w

(array([ 9, 10]), array([11, 12]))

In [23]:
np.dot(v,w)

219

In [24]:
np.dot(x,v)

array([29, 67])

In [25]:
x = np.array([[1,2],[3,4]])

print (np.sum(x))  # Compute sum of all elements; prints "10"
print (np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print (np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [26]:
x = np.array([[1,2], [3,4]])
x.T

array([[1, 3],
       [2, 4]])

In [27]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.reshape(a,6)

array([1, 2, 3, 4, 5, 6])

In [29]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.reshape(a,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#done