In [1]:
import numpy as np

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2;

a[:2,1:3]

array([[2, 3],
       [6, 7]])

In [4]:
b=a[:2,1:3]
a[0,0]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

1

In [6]:
b[0,0]=10
a[0,1]

10

In [9]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array

rank1=a[1,:]
rank1

array([5, 6, 7, 8])

In [10]:
rank1.shape

(4,)

In [11]:
rank2=a[1:2,:]
rank2

array([[5, 6, 7, 8]])

In [12]:
rank2.shape

(1, 4)

In [13]:
a = np.array([[1,2], [3, 4], [5, 6]])
a.shape

(3, 2)

In [14]:
#index array indexing
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [16]:
# The above example of integer array indexing is equivalent to this:
a[0, 0], a[1, 1], a[2, 0]

(1, 4, 5)

In [17]:
#other way of ding it
a[np.arange(3),[0,1,0]]

array([1, 4, 5])

In [28]:
# Mutate one element from each row of a using the indices in b
a[np.arange(3), [0,1,0]] += 10
a

array([[11,  2],
       [ 3, 14],
       [15,  6]])

In [29]:
# Find the elements of a that are bigger than 2;
# this returns a numpy array of Booleans of the same
# shape as a, where each slot of bool_idx tells
# whether that element of a is > 2.
bool_idx = (a > 2) 
bool_idx

array([[ True, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [31]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
a[bool_idx]

array([11,  3, 14, 15,  6])

In [32]:
#other way
a[a > 2] 

array([11,  3, 14, 15,  6])

In [33]:
#datatype of numpy 
a.dtype

dtype('int32')

In [34]:
x = np.array([1, 2], dtype=np.int64) 
x.dtype

dtype('int64')

In [35]:
#done