In [5]:
import numpy as np

x=np.arange(10,20) # arange(20)-->1 to 20 
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
x=np.linspace(1,10) #start 1 and stop 10
x

array([  1.        ,   1.18367347,   1.36734694,   1.55102041,
         1.73469388,   1.91836735,   2.10204082,   2.28571429,
         2.46938776,   2.65306122,   2.83673469,   3.02040816,
         3.20408163,   3.3877551 ,   3.57142857,   3.75510204,
         3.93877551,   4.12244898,   4.30612245,   4.48979592,
         4.67346939,   4.85714286,   5.04081633,   5.2244898 ,
         5.40816327,   5.59183673,   5.7755102 ,   5.95918367,
         6.14285714,   6.32653061,   6.51020408,   6.69387755,
         6.87755102,   7.06122449,   7.24489796,   7.42857143,
         7.6122449 ,   7.79591837,   7.97959184,   8.16326531,
         8.34693878,   8.53061224,   8.71428571,   8.89795918,
         9.08163265,   9.26530612,   9.44897959,   9.63265306,
         9.81632653,  10.        ])

In [9]:
x=np.linspace(1,10,7) #start 1 and stop 10 with 7 values
x

array([  1. ,   2.5,   4. ,   5.5,   7. ,   8.5,  10. ])

In [10]:
x=np.linspace(1,10,7,endpoint=False) #excluding 10(endpoint) value
x

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571])

In [13]:
samples, spacing = np.linspace(1, 10,7, retstep=True) #returns tuple gives space between two values
samples

array([  1. ,   2.5,   4. ,   5.5,   7. ,   8.5,  10. ])

In [14]:
spacing

1.5

In [15]:
x=np.zeros((3,3))
x

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
y=x.copy()# creates a newobject y
y is x

False

In [19]:
y=x #here x and y are same 
y is x

True

In [22]:
x, y, z = np.loadtxt('C:/Users/Madhu/Desktop/data.txt',
                    skiprows=1,
                    unpack=True)
x

array([ 0.2536,  0.4839,  0.1292,  0.1781,  0.6253])

In [31]:
x, y, z = np.genfromtxt('C:/Users/Madhu/Desktop/data.txt',
                      skip_header=1,
                      filling_values=-1,unpack=True) # for missing values
z

array([ 0.3857, -1.    ,  0.5929,  0.8928,  0.8791])

In [ ]:
#done