In [9]:
import numpy as np

#Numpy array creation
my_array=np.array([1,2,3]) #rank 1 array
my_array

array([1, 2, 3])

In [10]:
my_array1=np.array([[1,2,3],
                    [2,3,0]]) #rank 2 array
my_array1

array([[1, 2, 3],
       [2, 3, 0]])

In [15]:
a=np.zeros((2,3))#2 rows 3 colums
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [17]:
a=np.zeros([2,2,5,6])# 5 rows 6 columns -->1 block -->2 rows 2 colums -->2 blocks * 2blocks= 4 blocks
a

array([[[[ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.]]]])

In [19]:
a=np.ones((3,3)) # 3 rows ans 3 columns
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
b=np.ones([2,2,5,6])
b

array([[[[ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.]]],


       [[[ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.]]]])

In [21]:
a=np.full((2,2),7)
a

C:\Users\Madhu\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 7.,  7.],
       [ 7.,  7.]])

In [22]:
b=np.full([2,2,3,4],7)
b

C:\Users\Madhu\AppData\Local\Continuum\Anaconda3\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full([2, 2, 3, 4], 7) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[[[ 7.,  7.,  7.,  7.],
         [ 7.,  7.,  7.,  7.],
         [ 7.,  7.,  7.,  7.]],

        [[ 7.,  7.,  7.,  7.],
         [ 7.,  7.,  7.,  7.],
         [ 7.,  7.,  7.,  7.]]],


       [[[ 7.,  7.,  7.,  7.],
         [ 7.,  7.,  7.,  7.],
         [ 7.,  7.,  7.,  7.]],

        [[ 7.,  7.,  7.,  7.],
         [ 7.,  7.,  7.,  7.],
         [ 7.,  7.,  7.,  7.]]]])

In [23]:
a =np.eye(2) #creates identity matrix
a

array([[ 1.,  0.],
       [ 0.,  1.]])

In [27]:
a=np.random.random((2,2)) #creates random values between 0 and 1
a

array([[ 0.1127539 ,  0.22045691],
       [ 0.938396  ,  0.59100046]])

In [28]:
b=np.random.random([2,2])
b

array([[ 0.40637874,  0.12808159],
       [ 0.90015091,  0.15754539]])

In [29]:
b=np.random.random([2,2,3])
b

array([[[  4.51078115e-01,   8.61412487e-01,   1.22777176e-01],
        [  4.36225396e-01,   3.58512955e-01,   6.64496350e-04]],

       [[  3.38728015e-01,   5.52690619e-01,   2.45450717e-01],
        [  3.56059292e-01,   7.19209110e-01,   7.19072713e-01]]])

In [30]:
b=np.random.random([2,2,3,3])
b

array([[[[ 0.17087668,  0.21368717,  0.55290831],
         [ 0.59837578,  0.05054088,  0.85075484],
         [ 0.46000426,  0.11347536,  0.77387342]],

        [[ 0.41838707,  0.86928883,  0.02210635],
         [ 0.08060726,  0.58753425,  0.0663617 ],
         [ 0.48987666,  0.54992788,  0.61669236]]],


       [[[ 0.76197587,  0.78630274,  0.36385055],
         [ 0.24487299,  0.18062016,  0.61464046],
         [ 0.57429763,  0.67909001,  0.13543418]],

        [[ 0.64943623,  0.59246389,  0.26649633],
         [ 0.25809336,  0.57868682,  0.17626231],
         [ 0.6960004 ,  0.24855071,  0.86071949]]]])